title: Antigone-Blog
description: "Just a simple blog"
author:
  name: "Antigone"
  email: "wenyuyang681@gmail.com"
  url: "antigone4224.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 12
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Antigone4224"
year : "2023"
